"""
This type stub file was generated by pyright.
"""

from typing import Callable, Generic, TypeVar

A = TypeVar("A")
B = TypeVar("B")
class Identity(Generic[A]):
    """The identiy functor applies functions to its contents
    with no additional funtionality. It is the trivial or null
    functor.

    It is needed for lenses to be able to set values.
    """
    __slots__ = ...
    def __init__(self, item: A) -> None:
        ...
    
    def __repr__(self) -> str:
        ...
    
    def __eq__(self, other: object) -> bool:
        ...
    
    def map(self, fn: Callable[[A], B]) -> Identity[B]:
        ...
    
    @classmethod
    def pure(cls, item: A) -> Identity[A]:
        ...
    
    def apply(self, fn: Identity[Callable[[A], B]]) -> Identity[B]:
        ...
    
    def unwrap(self) -> A:
        ...
    


