"""
This type stub file was generated by pyright.
"""

from .base import ComposedLens, Equality, ErrorIso, Fold, Getter, Isomorphism, Lens, LensLike, Prism, Review, Setter, Traversal, TrivialIso
from .folds import IterableFold
from .isomorphisms import DecodeIso, JsonIso, NormalisingIso
from .prisms import FilteringPrism, InstancePrism, JustPrism
from .setters import ForkedSetter
from .true_lenses import ContainsLens, GetattrLens, GetitemLens, GetitemOrElseLens, ItemByValueLens, ItemLens, PartsLens, TupleLens
from .traversals import EachTraversal, GetZoomAttrTraversal, ItemsTraversal, RecurTraversal, ZoomAttrTraversal, ZoomTraversal

