"""
This type stub file was generated by pyright.
"""

from .base import Setter

__all__ = ["ForkedSetter"]
class ForkedSetter(Setter):
    """A setter representing the parallel composition of several sub-lenses.

    >>> import lenses
    >>> gi = lenses.optics.GetitemLens
    >>> fs = ForkedSetter(gi(0) & gi(1), gi(2))
    >>> fs
    ForkedSetter(GetitemLens(0) & GetitemLens(1), GetitemLens(2))
    >>> state = [[0, 0], 0, 0]
    >>> fs.set(state, 1)
    [[0, 1], 0, 1]
    """
    def __init__(self, *lenses) -> None:
        ...
    
    def func(self, f, state): # -> Identity[Unknown]:
        ...
    
    def __repr__(self): # -> str:
        ...
    


